### ISSUE TITLE
Add documentation comments for TypeScript SDK

### ISSUE THREAD

**Issue by radu-matei** [spinframework/spin-js-sdk#129]
ref https://tsdoc.org/

**Comment by karthik2804** [comment]
There are some issues with this because of the way the SDK is setup. `typedoc` spits out only the documentation for the exported items which in our case is a very small subset of the API (4 interfaces recalling from memory). I need to look into the plugin ecosystem to see if I can find something that we can use to export all the required interfaces. if not we may need to write our own plugin or build on top of `tsdoc`.

**Comment by karthik2804** [comment]
The new SDK comes with tsdoc and the docs are published to [https:/fermyon.github.io/spin-js-sdk](https:/fermyon.github.io/spin-js-sdk)
the v1 SDK docs can be found at [https:/fermyon.github.io/spin-js-sdk/v1](https:/fermyon.github.io/spin-js-sdk/v1)
