### ISSUE TITLE
Alias for `fetch`

### ISSUE THREAD

**Issue by radu-matei** [spinframework/spin-js-sdk#3]
Do we want to consider aliasing `spinSdk.http.send` to `fetch` (or rather adapting it to the same signature)?

Does that set an expectation that certain functions are available, or is it helpful to have familiar constructs?

**Comment by dicej** [comment]
Yeah, I thought about that, but `fetch` is asynchronous (i.e. it returns a `Promise`), and I wasn't sure how that would look given that component model async is still in the design phase.  I guess it could just return an already-fulfilled `Promise`?

I'm also looking at emulating Node APIs for filesystem access.  As you may know, Node has three different APIs for that: `Promise`-based, callback-based, and synchronous.  I was planning to just implement a subset of the synchronous API, since it's going to be synchronous (from the guest perspective) anyway, but on the other hand the synchronous API is probably the least popular in terms of existing code in the wild.

Should we provide a `Promise`-based API wherever applicable, with every function returning an already-fulfilled `Promise`?  We'd just be pretending it's asynchronous when it really isn't, but then later when we have true async support we can add that in without forcing anybody to change their code.

**Comment by dicej** [comment]
It took a while to figure out how to deal with `Promise`s using the QuickJS C API, but I got it working.  We now provide a `fetch` function which only has a tiny subset of the standard functionality, but handles the common case just fine.

I'll follow the same pattern for other applicable APIs.

**Comment by radu-matei** [comment]
Do we want our `fetch` to implement the Node and browser `fetch` API?
ref https://github.com/nodejs/undici/blob/main/types/fetch.d.ts and https://developer.mozilla.org/en-US/docs/Web/API/fetch

**Comment by dicej** [comment]
My goal for `fetch` and all other "standard" APIs (e.g. `URL`, Node's `fs`, etc.) is to provide a useful, strict subset of the standard API.  For example, we can guarantee that any code written to use Spin's `fetch` will also work in a browser or on Node, but not necessarily vice-versa.  Implementing all those APIs fully from scratch would be a *big* effort, and we'd probably end up throwing most of it away once we switch to SpiderMonkey (since we'd just use SpiderMonkey's implementation at that point).

We can certainly expand the implementations as needed (e.g. to support other third party libraries), but I'd be wary of trying to implement the entire `fetch` API in one go -- it's a pretty huge beast that pulls in a lot of other APIs.
