### ISSUE TITLE
`TextEncoder` and `TextDecoder`

### ISSUE THREAD

**Issue by radu-matei** [spinframework/spin-js-sdk#5]
I'm trying to use an external library that needs a `TextDecoder`, and I had the imports in the following order:

```
import <some library that needs TextEncoder and TextDecoder>;
import { TextEncoder, TextDecoder } from "fast-text-encoding";

```

Building this results in `TextDecoder not defined`:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Uncaught ReferenceError: 'TextDecoder' is not defined
    at <anonymous> (script.js:1645)
    at <anonymous> (script.js:1882)
    at <eval> (script.js:1885)
', crates/spin-js-engine/src/lib.rs:193:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: the `wizer.initialize` function trapped

Caused by:
    wasm trap: wasm `unreachable` instruction executed
    wasm backtrace:
        0: 0x188002 - <unknown>!__rust_start_panic
    note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable to may show more debugging information
```

Swapping the imports order works around this issue. However, it would be great if `TextEncoder`, `TextDecoder` and others would be available without having to 1) care about the import order, and 2) manually add it as a dependency.

As a side note, I am bumping into a similar issue for `new URL`, but so far haven't been able to import a package that works around the issue.

**Comment by dicej** [comment]
Honestly I wouldn't expect `import` to work at all (regardless of order) for `fast-text-encoding` since it is not packaged as a JS module but instead as an old-school script.  The only way you can use it AFAIK is via `require("fast-text-encoding")` like we do [here](https://github.com/fermyon/spin-js-sdk/blob/25bf4f19ec5bff01a2e5e20262ff4f96b98e3382/src/index.js#L1).

But yes, I agree that we should just make it part of the SDK instead of forcing the app developer to explicitly `require` it.
